
package com.dxc.plm.linglong.test.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestService", targetNamespace = "http://service.test.linglong.plm.dxc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SimpleTestService")
    @WebResult(name = "SimpleTestServiceResult", targetNamespace = "")
    @RequestWrapper(localName = "SimpleTestService", targetNamespace = "http://service.test.linglong.plm.dxc.com/", className = "com.dxc.plm.linglong.test.service.SimpleTestService")
    @ResponseWrapper(localName = "SimpleTestServiceResponse", targetNamespace = "http://service.test.linglong.plm.dxc.com/", className = "com.dxc.plm.linglong.test.service.SimpleTestServiceResponse")
    @Action(input = "http://service.test.linglong.plm.dxc.com/TestService/SimpleTestServiceRequest", output = "http://service.test.linglong.plm.dxc.com/TestService/SimpleTestServiceResponse")
    public String simpleTestService(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param testServiceRequest
     * @return
     *     returns com.dxc.plm.linglong.test.service.TestServiceResult
     */
    @WebMethod(operationName = "TestService")
    @WebResult(name = "TestServiceResult", targetNamespace = "")
    @RequestWrapper(localName = "TestService", targetNamespace = "http://service.test.linglong.plm.dxc.com/", className = "com.dxc.plm.linglong.test.service.TestService_Type")
    @ResponseWrapper(localName = "TestServiceResponse", targetNamespace = "http://service.test.linglong.plm.dxc.com/", className = "com.dxc.plm.linglong.test.service.TestServiceResponse")
    @Action(input = "http://service.test.linglong.plm.dxc.com/TestService/TestServiceRequest", output = "http://service.test.linglong.plm.dxc.com/TestService/TestServiceResponse")
    public TestServiceResult testService(
        @WebParam(name = "TestServiceRequest", targetNamespace = "")
        TestServiceRequest testServiceRequest);

}
